[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
coin_mint = "38fPj6DPz5FXwBzYnaNK67ifYVoffEhJMuFDacqkFubk"
crank_oracle = "EqA8JFvh2XkxQNLohZ4gJprWSv6z897BsjfBhnQDoDPZ"

[programs.localnet]
testy_token = "HgxUgnUiQHYxx4NmLEcM1J2Jt3fyEzkSzZiVBtQARCmA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
crank = "npx ts-node ./scripts/managedUpdate.ts --feedId 0xaf3a39b12f5c052d81eb8c62bb86f4691fce2c2e0c88b39f83801978b6f203c3"
mint = "npx ts-node scripts/mint-launch.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
