[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
coin_mint = "8kNySBN4Zjd8jnWgrE5LcafLNTT16Lhgwhna1tqyn8we"
crank_oracle = "GsUHrYWJVUeMkDAFDRq2s8hJXwmg8fYCQjJ6ApbFK1as"
staking = "8CzYeKYrQieo6wXsQZ4fJB1otLgUwHAf5L1R8Sht1LX1"

[programs.localnet]
staking = "8CzYeKYrQieo6wXsQZ4fJB1otLgUwHAf5L1R8Sht1LX1"
testy_token = "Eb7SiNnSwCoKobhG8dDarPQxErqmnzK7kJ1SRW9vEpdS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
## update CRANK_ORACLE_PROGRAM_ID in mint
bount = "npx ts-node ./scripts/mev-keeper.ts"
crank = "npx ts-node ./scripts/managedUpdate.ts --feedId 0xaf3a39b12f5c052d81eb8c62bb86f4691fce2c2e0c88b39f83801978b6f203c3"
init = "npx ts-node ./scripts/initialize.ts && npx ts-node ./scripts/init-bounty.ts"
mint = "npx ts-node scripts/mint-launch.ts"
pool = "npx ts-node ./scripts/pool-init.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
## use with "-- 2"
set-oracle = "npx ts-node ./scripts/set-oracle-state.ts"
test-staking = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/staking.ts"
